---
title: "Deep Transcriptomic Atlas of Substantia Nigra in Parkinson's Disease"
author: "Viola Volpato"
date: 'Last update: `r date()`'
output:
  html_document:
    fig_height: 5
    fig_width: 5
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
      toc_depth: 5
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---


```{r clean r session, include=FALSE}
rm(list = ls())
```

### Install and load library

```{r load lib, echo=TRUE}
library(ggplot2)
library(Seurat)
devtools::install_github("rpolicastro/scProportionTest")
library("scProportionTest")
library(RColorBrewer)
```


### Load data

```{r get raw data, echo=TRUE}
load("/nfs/dri/02/rdscw/shared/webber/SNatlas_icell8_Novaseq/manuscript_data/sn_atlas_unprocessed.RData")
```

### DATA INTEGRATION BY DISEASE (Figure 1)

# Seurat fast integration using reciprocal PCA (see https://satijalab.org/seurat/articles/integration_rpca)

```{r perform data integration,echo=TRUE}

data_all <- sn_atlas_unprocessed
data_all.list <- SplitObject(data_all, split.by = "Disease")

# normalize and identify variable features for each dataset independently
data_all.list <- lapply(X = data_all.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

# select features that are repeatedly variable across datasets for integration run PCA on each
# dataset using these features
features <- SelectIntegrationFeatures(object.list = data_all.list)
data_all.list <- lapply(X = data_all.list, FUN = function(x) {
    x <- ScaleData(x, features = features, verbose = FALSE)
    x <- RunPCA(x, features = features, verbose = FALSE)
})

anchors_all <- FindIntegrationAnchors(object.list = data_all.list, anchor.features = features, reduction = "rpca", k.anchor=20)
# this command creates an 'integrated' data assay
combined_all <- IntegrateData(anchorset = anchors_all)

DefaultAssay(combined_all) <- "integrated"

# Run the standard workflow for visualization and clustering
combined_all <- ScaleData(combined_all, verbose = FALSE)
combined_all <- RunPCA(combined_all, npcs = 40, verbose = FALSE)
combined_all <- RunUMAP(combined_all, reduction = "pca", dims = 1:40)
combined_all <- FindNeighbors(combined_all, reduction = "pca", dims = 1:40)
combined_all <- FindClusters(combined_all, resolution = 0.5)

``` 

### Cell type identification

```{r cell type identification, echo=TRUE}

DefaultAssay(combined_all) <- "RNA"

markersALL<-c("GFRA2","CALCR","CRYM","CCDC68","PPP1R17","TRHR","TH","GRIN2C","SLC18A2","DCX","LMX1A","GAD2","GAD1","NTSR1","SLC6A3","KCNJ6","PITX3","CHRNA4","LMX1B","GRIK3","ALDH1A1","AQP4","GFAP","VCAN","MOBP","MOG","CSF1R","CD8A","PTPRC","CLDN5","PTH1R")

DotPlot(combined_all, features = markersALL, dot.scale = 8) +
    RotatedAxis()

combined_all$cluster <- Idents(combined_all)
cellType <- c("ODC","ODC","DaN","DaN","Microglia","Astrocyte","OPC","GABA","DaN","DaN","DaN","Tcell")
names(cellType) <- levels(combined_all)
combined_all <- RenameIdents(combined_all, cellType)
combined_all$CellType<-Idents(combined_all)

DimPlot(combined_all, reduction = "umap", split.by = "Disease",group.by="CellType")

metadataALL<-as.data.frame(combined_all@meta.data)
genesALL<-as.matrix(GetAssayData(combined_all, slot = "counts"))

```

### Cell subtype identification

```{r subtype identification, echo=TRUE}

# TO DO FOR EACH MAIN CELL TYPE

metadataALL_tmp<-metadataALL[metadataALL$CellType=="DaN",]
metadataALL_tmp<-metadataALL_tmp[metadataALL_tmp$Sample_v2!="14_133",] # outlier sample in both UMAP plot of all DaNs and in following pseudotime analysis (still to investigate why)
genesALL_tmp<-genesALL[,colnames(genesALL)%in%rownames(metadataALL_tmp)]

tmp_cell <- CreateSeuratObject(counts = genesALL_tmp, min.cells = 0, min.features = 0,meta.data= metadataALL_tmp)

tmp_cell.list <- SplitObject(tmp_cell, split.by = "Disease")

tmp_cell.list <- lapply(X = tmp_cell.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

features <- SelectIntegrationFeatures(object.list = tmp_cell.list)
tmp_cell.list <- lapply(X = tmp_cell.list, FUN = function(x) {
    x <- ScaleData(x, features = features, verbose = FALSE)
    x <- RunPCA(x, features = features, verbose = FALSE)
})

tmp_cell.anchors <- FindIntegrationAnchors(object.list = tmp_cell.list, anchor.features = features, reduction = "rpca", k.anchor=40)
tmp_cell.combined <- IntegrateData(anchorset = tmp_cell.anchors) 

#tmp_cell.combined <- IntegrateData(anchorset = tmp_cell.anchors) # for odc
#tmp_cell.combined <- IntegrateData(anchorset = tmp_cell.anchors,k.weight=80) # for microglia
#tmp_cell.combined <- IntegrateData(anchorset = tmp_cell.anchors,k.weight=120) # for astrocytes

DefaultAssay(tmp_cell.combined) <- "integrated"

tmp_cell.combined <- ScaleData(tmp_cell.combined, verbose = FALSE)
tmp_cell.combined <- RunPCA(tmp_cell.combined, npcs = 40, verbose = FALSE)
tmp_cell.combined <- RunUMAP(tmp_cell.combined, reduction = "pca", dims = 1:40)
tmp_cell.combined <- FindNeighbors(tmp_cell.combined, reduction = "pca", dims = 1:40)
tmp_cell.combined <- FindClusters(tmp_cell.combined, resolution = 0.2)

DimPlot(tmp_cell.combined, reduction = "umap", split.by = "Disease",group.by="seurat_clusters")

DefaultAssay(tmp_cell.combined) <- "RNA"
dan_markers <- c("SOX6", "GRIA3", "DCX", "AGTR1", "LMX1B", "GRIK3", "RET", "GFRA2", "PITX3", "CHRNA4", "SLC18A2", "SLC6A3", "TH", "KCNJ6", "ALDH1A1", "TMEM255A", "LGI1",   "TMEFF2")
DotPlot(tmp_cell.combined, features = dan_markers, dot.scale = 8,idents = c(0,1,2,3)) + # clusters 4 and 5 are not used as too small and only present in ILBD_B3-4
    RotatedAxis()


# markers_ODC=c("PLXDC2","PLP1","SPARC","DHCR24","TUBA1A","PMP2","RBFOX1","AFF3","FMN1","PALM2","HHIP","OPALIN","LAMA2") # selected from https://www.biorxiv.org/content/10.1101/2022.03.22.485367v1.full.pdf

# markers_microglia=c("PTPRC","ITGAM","AIF1","C1QA","CTSS","CD14","CSF3R","ARGLU1","FAM46A","IFIT3","ISG15","MRC1","TNF","CD83","EGR2","TNFSF18","CCL8","TFRC","PCNA","RASGEF1C","AC008691.1", "TLN2","GPNMB","ACSL1","CXCR4","NTM", "MAGI2", "SCD", "PLP1","NRG3")  (check https://www.biorxiv.org/content/10.1101/2022.03.22.485367v1.full.pdf and https://www.nature.com/articles/s41467-020-19737-2) markers.to.plot=c("MRC1","IL10","ABCC4","CSF2RA","CSF3R","TFRC","KLF4","PTGS1","DOCK8","KCNQ1","PTPRC","GPNMB","SPP1","TYROBP","TREM2","TLR2","MS4A4A","IL13RA1","INPP5D","ITGAM","ADAP2","APBB1IP","SP140L","VAV1") # macrophage M2: "MRC1","IL10","ABCC4","CSF2RA","CSF3R","TFRC","KLF4","PTGS1","DOCK8"

# markers_astrocyte=c("GABRA2","EDNRB","PPFIA2","KCNJ16","BHLHE40","SLC6A11","PAK3","GRM5","PTPRT","FAT3","EPHA6","EPHB1","ADGRV1","SPOCK1","SPSB1","MYO1E","SLC24A2","ELMO1","NKAIN2","PLP1","S100B","TMSB4X") 


# load processed data file with all annotated cell subtypes
load("/nfs/dri/02/rdscw/shared/webber/SNatlas_icell8_Novaseq/manuscript_data/sn_atlas_processed.RData")


df<-data.frame(table(sn_atlas_processed$CellSubType,sn_atlas_processed$Disease))
# plot number_of_cells_byCellSubType_byDisease
ggplot(df, aes(x = Var1, y = Freq, fill=Var2)) + geom_bar(stat = "identity", position=position_dodge()) +  theme_minimal() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


```





