---
title: "Deep Transcriptomic Atlas of Substantia Nigra in Parkinson's Disease"
author: "Viola Volpato"
date: 'Last update: `r date()`'
output:
  html_document:
    fig_height: 5
    fig_width: 5
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
      toc_depth: 5
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---


```{r clean r session, include=FALSE}
rm(list = ls())
```

### Load data

```{r get raw data, echo=TRUE}
library(Seurat)
load("/gluster/dri02/rdscw/shared/webber/SNatlas_icell8_Novaseq/processed_data/raw_gene_expression.RData")
```

### DATA INTEGRATION ANALYSIS BY DISEASE 

```{r perform data integration,echo=TRUE}

data_all <- sn_atlas_unprocessed
data_all.list <- SplitObject(data_all, split.by = "Disease")

# normalize and identify variable features for each dataset independently
data_all.list <- lapply(X = data_all.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

# select features that are repeatedly variable across datasets for integration run PCA on each
# dataset using these features
features <- SelectIntegrationFeatures(object.list = data_all.list)
data_all.list <- lapply(X = data_all.list, FUN = function(x) {
    x <- ScaleData(x, features = features, verbose = FALSE)
    x <- RunPCA(x, features = features, verbose = FALSE)
})

anchors_all <- FindIntegrationAnchors(object.list = data_all.list, anchor.features = features, reduction = "rpca", k.anchor=40)
# this command creates an 'integrated' data assay
combined_all <- IntegrateData(anchorset = anchors_all)

DefaultAssay(combined_all) <- "integrated"

# Run the standard workflow for visualization and clustering
combined_all <- ScaleData(combined_all, verbose = FALSE)
combined_all <- RunPCA(combined_all, npcs = 40, verbose = FALSE)
combined_all <- RunUMAP(combined_all, reduction = "pca", dims = 1:40)
combined_all <- FindNeighbors(combined_all, reduction = "pca", dims = 1:40)
combined_all <- FindClusters(combined_all, resolution = 0.5)

``` 

### Cell type identification

```{r cell type identification, echo=TRUE}

DefaultAssay(combined_all) <- "RNA"

markersALL<-c("GFRA2","CALCR","CRYM","CCDC68","PPP1R17","TRHR","TH","GRIN2C","SLC18A2","DCX","LMX1A","GAD2","GAD1","NTSR1","SLC6A3","KCNJ6","PITX3","CHRNA4","LMX1B","GRIK3","ALDH1A1","AQP4","GFAP","VCAN","MOBP","MOG","CSF1R","CD8A","PTPRC","CLDN5","PTH1R")

DotPlot(combined_all, features = markersALL, dot.scale = 8) +
    RotatedAxis()

combined_all$cluster <- Idents(combined_all)
cellType <- c("ODC","ODC","DaN","DaN","Microglia","DaN","Astrocyte","OPC","GABA","DaN","Tcells")
names(cellType) <- levels(combined_all)
combined_all <- RenameIdents(combined_all, cellType)
combined_all$CellType<-Idents(combined_all)

DimPlot(combined_all, reduction = "umap", split.by = "Disease",group.by="CellType")

metadataALL<-as.data.frame(combined_all@meta.data)
genesALL<-as.matrix(GetAssayData(combined_all, slot = "counts"))

```

### Cell subtype identification

```{r subtype identification, echo=TRUE}

# TO DO FOR EACH MAIN CELL TYPE

metadataALL_tmp<-metadataALL[metadataALL$CellType=="DaN",]
genesALL_tmp<-genesALL[,colnames(genesALL)%in%rownames(metadataALL_tmp)]

tmp_cell <- CreateSeuratObject(counts = genesALL_tmp, min.cells = 0, min.features = 0,meta.data= metadataALL_tmp)

tmp_cell.list <- SplitObject(tmp_cell, split.by = "Disease")

tmp_cell.list <- lapply(X = tmp_cell.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

features <- SelectIntegrationFeatures(object.list = tmp_cell.list)
tmp_cell.list <- lapply(X = tmp_cell.list, FUN = function(x) {
    x <- ScaleData(x, features = features, verbose = FALSE)
    x <- RunPCA(x, features = features, verbose = FALSE)
})

tmp_cell.anchors <- FindIntegrationAnchors(object.list = tmp_cell.list, anchor.features = features, reduction = "rpca", k.anchor=40)
tmp_cell.combined <- IntegrateData(anchorset = tmp_cell.anchors) 

#tmp_cell.combined <- IntegrateData(anchorset = tmp_cell.anchors) # for odc
#tmp_cell.combined <- IntegrateData(anchorset = tmp_cell.anchors,k.weight=80) # for microglia
#tmp_cell.combined <- IntegrateData(anchorset = tmp_cell.anchors,k.weight=120) # for astro

DefaultAssay(tmp_cell.combined) <- "integrated"

tmp_cell.combined <- ScaleData(tmp_cell.combined, verbose = FALSE)
tmp_cell.combined <- RunPCA(tmp_cell.combined, npcs = 40, verbose = FALSE)
tmp_cell.combined <- RunUMAP(tmp_cell.combined, reduction = "pca", dims = 1:40)
tmp_cell.combined <- FindNeighbors(tmp_cell.combined, reduction = "pca", dims = 1:40)
tmp_cell.combined <- FindClusters(tmp_cell.combined, resolution = 0.2)

DimPlot(tmp_cell.combined, reduction = "umap", split.by = "Disease",group.by="seurat_clusters")

DefaultAssay(tmp_cell.combined) <- "RNA"
dan_markers <- c("SOX6", "GRIA3", "DCX", "AGTR1", "LMX1B", "GRIK3", "RET", "GFRA2", "PITX3", "CHRNA4", "SLC18A2", "SLC6A3", "TH", "KCNJ6", "ALDH1A1", "TMEM255A", "LGI1",   "TMEFF2")
DotPlot(tmp_cell.combined, features = dan_markers, dot.scale = 8) +
    RotatedAxis()


# load processed data file with all annotated cell subtypes
load("/gluster/dri02/rdscw/shared/webber/SNatlas_icell8_Novaseq/processed_data/SN_deep_atlas_Nov2022.RData")

DimPlot(sn_atlas, reduction = "umap", split.by = "Disease",group.by="CellSubType")

```


### Find cell type specific gene markers

```{r gene markers, echo=TRUE}

DefaultAssay(combined_all) <- "RNA"
Idents(combined_all)<-combined_all$CellType
clusterALLMarkers <- FindAllMarkers(combined_all, only.pos = FALSE, min.pct = 0.1, thresh.use = 0.2)

```

### Changes in cell type proportions

```{r cell_prop, echo=TRUE}

library("scProportionTest")
prop_test <- sc_utils(combined_all)

prop_test <- permutation_test(
	prop_test, cluster_identity = "CellSubType",
	sample_1 = "CTR", sample_2 = "PD_B5-6",
	sample_identity = "Disease"
)
```

### Find DEG CTR vs PD within each cell type

```{r deg_by_cellType, echo=TRUE}
combined_all$clust.disease <- paste(Idents(combined_all), combined_all$Disease, sep = "_")
combined_all$cluster <- Idents(combined_all)
Idents(combined_all) <- "clust.disease"

CTRvsPD56_DaN <- FindMarkers(combined_all, ident.1 = "DaN_CTR", ident.2 = "DaN_PD_B5-6", verbose = FALSE)

```


