---
title: "Deep Transcriptomic Atlas of Substantia Nigra in Parkinson's Disease"
author: "Viola Volpato"
date: 'Last update: `r date()`'
output:
  html_document:
    fig_height: 5
    fig_width: 5
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
      toc_depth: 5
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---


```{r clean r session, include=FALSE}
rm(list = ls())
```

### Install and load library

```{r load lib, echo=TRUE}
library(ggplot2)
library(Seurat)
library(RColorBrewer)
```


### Load data

```{r get raw data, echo=TRUE}
load("/nfs/dri/02/rdscw/shared/webber/SNatlas_icell8_Novaseq/manuscript_data/sn_atlas_processed.RData")

sn_atlas_processed <- NormalizeData(sn_atlas_processed)
sn_atlas_processed <- FindVariableFeatures(sn_atlas_processed, selection.method = "vst", nfeatures = 2000)
sn_atlas_processed <- ScaleData(sn_atlas_processed)
sn_atlas_processed <- RunPCA(sn_atlas_processed, features = VariableFeatures(object = sn_atlas_processed))
sn_atlas_processed <- FindNeighbors(sn_atlas_processed, dims = 1:10)
sn_atlas_processed <- FindClusters(sn_atlas_processed, resolution = 0.6)
sn_atlas_processed <- RunUMAP(sn_atlas_processed, dims = 1:10)

```

### Find cell type specific gene markers

```{r gene markers, echo=TRUE}

# Method 1 (used in the manuscript):
# to be done for each cell type and subtype in controls

# level 1:

list_w_stat<-c()
df_w_test<-c()
signed_rank = function(x) sign(x) * rank(abs(x))
metadataALL<-as.data.frame(sn_atlas_processed@meta.data)
metadataALL_CTR<-metadataALL[metadataALL$Disease=="CTR",]
data<-as.matrix(GetAssayData(sn_atlas_processed, slot = "counts"))
data<-data[,colnames(data)%in%rownames(metadataALL_CTR)]
list_cell <- as.array(unique(metadataALL_CTR$CellType))
list_gene <- row.names(data)

compute_w_val<-function(gene_ref,cell_ref,matrix_expr,info_cell) {
    n_cell<- ncol(data)
    X<- matrix(-1, nrow = n_cell, ncol = 1)
    X[which(info_cell$CellSubType==cell_ref),1]<-1
    Y=t(data[gene_ref,])
    df<-data.frame(y=t(Y),x=X)
    colnames(df)<-c("y","x")
    linearMod <- lm(signed_rank(y) ~ x, data=df)
    val<-summary(linearMod)
    list_val<-val$coefficients[2,3]
    return(val$coefficients[2,3]) ## w-statisc value
}

for (i in c(1:length(list_cell))) {
    cell_ref=list_cell[i]
    print("W test")
    print(list_cell[i])
    list_w_stat<-sapply(list_gene,compute_w_val,cell_ref=list_cell[i],matrix_expr=data,info_cell=metadataALL_CTR)
    if(!exists("df_w_test")) {
        df_w_test<-data.frame(list_w_stat)
    } else {
        df_w_test<-cbind(df_w_test,list_w_stat)
    }
}
colnames(df_w_test) <- list_cell
write.table(df_w_test,"Wtest_level1",quote=F,sep="\t")

# level 2:

list_w_stat<-c()
df_w_test<-c()
signed_rank = function(x) sign(x) * rank(abs(x))
metadataALL<-as.data.frame(sn_atlas_processed@meta.data)
metadataALL_CTR<-metadataALL[metadataALL$Disease=="CTR",]
metadataALL_CTR<-metadataALL_CTR[metadataALL_CTR$CellType=="ODC",]
data<-as.matrix(GetAssayData(sn_atlas_processed, slot = "counts"))
data<-data[,colnames(data)%in%rownames(metadataALL_CTR)]
list_cell <- as.array(unique(metadataALL_CTR$CellSubType))
list_gene <- row.names(data)

compute_w_val<-function(gene_ref,cell_ref,matrix_expr,info_cell) {
    n_cell<- ncol(data)
    X<- matrix(-1, nrow = n_cell, ncol = 1)
    X[which(info_cell$CellSubType==cell_ref),1]<-1
    Y=t(data[gene_ref,])
    df<-data.frame(y=t(Y),x=X)
    colnames(df)<-c("y","x")
    linearMod <- lm(signed_rank(y) ~ x, data=df)
    val<-summary(linearMod)
    list_val<-val$coefficients[2,3]
    return(val$coefficients[2,3]) ## w-statisc value
}

for (i in c(1:length(list_cell))) {
    cell_ref=list_cell[i]
    print("W test")
    print(list_cell[i])
    list_w_stat<-sapply(list_gene,compute_w_val,cell_ref=list_cell[i],matrix_expr=data,info_cell=metadataALL_CTR)
    if(!exists("df_w_test")) {
        df_w_test<-data.frame(list_w_stat)
    } else {
        df_w_test<-cbind(df_w_test,list_w_stat)
    }
}
colnames(df_w_test) <- list_cell
write.table(df_w_test,"Wtest_ODCs",quote=F,sep="\t")



# Method 2:

Idents(sn_atlas_processed)<-sn_atlas_processed$CellType
clusterALLMarkers <- FindAllMarkers(sn_atlas_processed, only.pos = FALSE, min.pct = 0.1, thresh.use = 0.2)

```

### Prepare for MAGMA analysis

```{r magma, echo=TRUE}

# level 1:

df_w_test_2p<-data.frame(cellt=c(rep("ODC",500),rep("Astrocyte",500),rep("DaN",500),rep("GABA",500),rep("OPC",500),rep("Microglia",500),rep("Tcell",500)),id=c(rownames(df_w_test[order(-df_w_test$ODC),])[1:500],rownames(df_w_test[order(-df_w_test$Astrocyte),])[1:500],rownames(df_w_test[order(-df_w_test$DaN),])[1:500],rownames(df_w_test[order(-df_w_test$GABA),])[1:500],rownames(df_w_test[order(-df_w_test$OPC),])[1:500],rownames(df_w_test[order(-df_w_test$Microglia),])[1:500],rownames(df_w_test[order(-df_w_test$Tcell),])[1:500]))

NCBI37.3.gene.loc<-read.delim("NCBI37.3.gene.loc",h=F)
names(NCBI37.3.gene.loc)[6]<-"id"
df<-merge(df_w_test_2p[,1:2],NCBI37.3.gene.loc,by=c("id"))
list_gene<-c()
for(m in unique(df$cellt)){
 val<-c(m,as.character(df[df$cellt==m,3]))
 val<-paste(val,collapse =" ")
 list_gene<-c(list_gene,val)
}
write.table(data.frame(list_gene),file="input_magma_level1_2p",quote=FALSE,row.names=FALSE,col.names=FALSE,sep="\t")

```

### Cell type-specific PPI networks

```{r cellt_PPI, echo=TRUE}
library(igraph)

# to be done for DaN_3, ODC_2 and OPC (where PD genetic risk converged)

ppi_net<-read.delim("ppi_net_new2023short",h=F)
ppi_net_dan3top1000<-ppi_net[ppi_net[,1]%in%rownames(df_w_test_DaN[oder(-df_w_test_DaN$DaN_3),])[1:1000] & ppi_net[,2]%in%rownames(df_w_test_DaN[oder(-df_w_test_DaN$DaN_3),])[1:1000] ,]
ppi_net_dan3top1000_genes<-unique(c(as.character(ppi_net_dan3top1000[,1]),as.character(ppi_net_dan3top1000[,2])))

net_1 <- graph_from_data_frame(d= ppi_net_dan3top1000, vertices= ppi_net_dan3top1000_genes, directed=F)
cl_net_1<-cluster_louvain(net_1)
memb_net_1<-as.matrix(membership(cl_net_1))

memb_net_dan3top1000ppi_df<-data.frame(id=rownames(memb_net_1),module=memb_net_1)


```


### Changes in cell type proportions

```{r cell_prop, echo=TRUE}

library("scProportionTest")
library(speckle)
library(limma)
library(ggplot2)

# Method 1, use FDR-corrected p-values:
prop_test <- sc_utils(sn_atlas_processed)

prop_test <- permutation_test(
	prop_test, cluster_identity = "CellSubType",
	sample_1 = "CTR", sample_2 = "PD_B5-6",
	sample_identity = "Disease"
)

# Method 2, use nominal p-values:
sn_atlas_processed_tmp<-subset(sn_atlas_processed,subset=Disease=="CTR" | Disease=="PD_B5-6")
propeller(clusters = sn_atlas_processed_tmp$CellSubType, sample = sn_atlas_processed_tmp$Sample_v2, 
          group = sn_atlas_processed_tmp$Disease)

plotCellTypeProps(clusters=sn_atlas_processed_tmp$seurat_clusters, sample=sn_atlas_processed_tmp$Disease)

sn_atlas_processed_tmp<-subset(sn_atlas_processed,subset=Disease=="CTR" | Disease=="PD_B5-6")
df_tmp<-data.frame(table(sn_atlas_processed_tmp$CellSubType))
prop_df_ctr_pd56$prop<-prop_df_ctr_pd56$Freq/df_tmp$Freq*100
pdf("celltype_prop_CTR_PD56.pdf",6,3)
ggplot(data=prop_df_ctr_pd56, aes(x=Var1, y=prop, fill=Var2)) +
     geom_bar(stat="identity") + scale_fill_manual(values=c('mediumorchid','skyblue')) + theme(axis.text.x = element_text( color = "black",size = 10, angle = 45,hjust=1))
dev.off()


props.data <- getTransformedProps(clusters=sn_atlas_processed_tmp$CellSubType, sample=sn_atlas_processed_tmp$Sample_v2,
                                  transform="logit")
df<-data.frame(props.data$Proportions)
df$disease<-ifelse(df$sample=="15_013" | df$sample=="PD_792" | df$sample=="18_005" | df$sample=="PD_714" | df$sample=="PD_816","PD56","CTR")

pdf("proportion_changes_propeller.pdf",10,3)
ggplot(df, aes(x=clusters, y=Freq, color=disease)) +
     geom_boxplot(position=position_dodge(0.8))+
     geom_jitter(position=position_dodge(0.8))+
     scale_color_manual(values=c("mediumorchid","skyblue"))+
     theme(axis.text.x = element_text( color = "black",size = 10, angle = 45,hjust=1))
dev.off()

```

### Find DEGs CTR vs PD within each cell type

```{r deg_by_cellType, echo=TRUE}

# level 1:
sn_atlas_processed$clust.disease <- paste(sn_atlas_processed$CellType, sn_atlas_processed$Disease, sep = "_")
sn_atlas_processed$cluster <- Idents(sn_atlas_processed)
Idents(sn_atlas_processed) <- "clust.disease"

CTRvsPD56_DaN <- FindMarkers(sn_atlas_processed, ident.1 = "DaN_CTR", ident.2 = "DaN_PD_B5-6", verbose = FALSE)
CTRvsPD56_ODC <- FindMarkers(sn_atlas_processed, ident.1 = "ODC_CTR", ident.2 = "ODC_PD_B5-6", verbose = FALSE)
CTRvsPD56_Astrocyte <- FindMarkers(sn_atlas_processed, ident.1 = "Astrocyte_CTR", ident.2 = "Astrocyte_PD_B5-6", verbose = FALSE)
CTRvsPD56_Microglia <- FindMarkers(sn_atlas_processed, ident.1 = "Microglia_CTR", ident.2 = "Microglia_PD_B5-6", verbose = FALSE)
CTRvsPD56_OPC <- FindMarkers(sn_atlas_processed, ident.1 = "OPC_CTR", ident.2 = "OPC_PD_B5-6", verbose = FALSE)
CTRvsPD56_GABA <- FindMarkers(sn_atlas_processed, ident.1 = "GABA_CTR", ident.2 = "GABA_PD_B5-6", verbose = FALSE)
CTRvsPD56_Tcell <- FindMarkers(sn_atlas_processed, ident.1 = "Tcell_CTR", ident.2 = "Tcell_PD_B5-6", verbose = FALSE)

# level 2:
sn_atlas_processed$clust.disease <- paste(sn_atlas_processed$CellSubType, sn_atlas_processed$Disease, sep = "_")
sn_atlas_processed$cluster <- Idents(sn_atlas_processed)
Idents(sn_atlas_processed) <- "clust.disease"

opc_d56<-FindMarkers(sn_atlas_processed,ident.1 = "OPC_PD_B5-6", ident.2 = "OPC_CTR")
tcell_d56<-FindMarkers(sn_atlas_processed,ident.1 = "Tcells_PD_B5-6", ident.2 = "Tcells_CTR")
odc2_d56<-FindMarkers(sn_atlas_processed,ident.1 = "ODC_2_PD_B5-6", ident.2 = "ODC_2_CTR")
odc1_d56<-FindMarkers(sn_atlas_processed,ident.1 = "ODC_1_PD_B5-6", ident.2 = "ODC_1_CTR")
odc0_d56<-FindMarkers(sn_atlas_processed,ident.1 = "ODC_0_PD_B5-6", ident.2 = "ODC_0_CTR")
micro2_d56<-FindMarkers(sn_atlas_processed,ident.1 = "Microglia_2_PD_B5-6", ident.2 = "Microglia_2_CTR")
micro1_d56<-FindMarkers(sn_atlas_processed,ident.1 = "Microglia_1_PD_B5-6", ident.2 = "Microglia_1_CTR")
micro0_d56<-FindMarkers(sn_atlas_processed,ident.1 = "Microglia_0_PD_B5-6", ident.2 = "Microglia_0_CTR")
gaba_d56<-FindMarkers(sn_atlas_processed,ident.1 = "GABA_PD_B5-6", ident.2 = "GABA_CTR")
astro3_d56<-FindMarkers(sn_atlas_processed,ident.1 = "Astrocyte_3_PD_B5-6", ident.2 = "Astrocyte_3_CTR")
astro2_d56<-FindMarkers(sn_atlas_processed,ident.1 = "Astrocyte_2_PD_B5-6", ident.2 = "Astrocyte_2_CTR")
astro0_d56<-FindMarkers(sn_atlas_processed,ident.1 = "Astrocyte_0_PD_B5-6", ident.2 = "Astrocyte_0_CTR")
astro1_d56<-FindMarkers(sn_atlas_processed,ident.1 = "Astrocyte_1_PD_B5-6", ident.2 = "Astrocyte_1_CTR")
dan2_d56<-FindMarkers(sn_atlas_processed,ident.1 = "DaN_2_PD_B5-6", ident.2 = "DaN_2_CTR")
dan1_d56<-FindMarkers(sn_atlas_processed,ident.1 = "DaN_1_PD_B5-6", ident.2 = "DaN_1_CTR")
dan0_d56<-FindMarkers(sn_atlas_processed,ident.1 = "DaN_0_PD_B5-6", ident.2 = "DaN_0_CTR")

deg_FC1andPadj1_numbers<-data.frame(celltype=c("Astrocyte_0","Astrocyte_1","Astrocyte_2","Astrocyte_3","DaN_0","DaN_1","DaN_2","DaN_3","GABA","Microglia_0","Microglia_1","Microglia_2","ODC_0","ODC_1","ODC_2","OPC","Tcells"),deg=c(length(astro0_d56[abs(astro0_d56$avg_log2FC)>=1 & astro0_d56$p_val_adj<=0.1,1]), length(astro1_d56[abs(astro1_d56$avg_log2FC)>=1 & astro1_d56$p_val_adj<=0.1,1]), 0, length(astro3_d56[abs(astro3_d56$avg_log2FC)>=1 & astro3_d56$p_val_adj<=0.1,1]), length(dan0_d56[abs(dan0_d56$avg_log2FC)>=1 & dan0_d56$p_val_adj<=0.1,1]), length(dan1_d56[abs(dan1_d56$avg_log2FC)>=1 & dan1_d56$p_val_adj<=0.1,1]), length(dan2_d56[abs(dan2_d56$avg_log2FC)>=1 & dan2_d56$p_val_adj<=0.1,1]), 0, length(gaba_d56[abs(gaba_d56$avg_log2FC)>=1 & gaba_d56$p_val_adj<=0.1,1]), length(micro0_d56[abs(micro0_d56$avg_log2FC)>=1 & micro0_d56$p_val_adj<=0.1,1]), length(micro1_d56[abs(micro1_d56$avg_log2FC)>=1 & micro1_d56$p_val_adj<=0.1,1]), length(micro2_d56[abs(micro2_d56$avg_log2FC)>=1 & micro2_d56$p_val_adj<=0.1,1]), length(odc0_d56[abs(odc0_d56$avg_log2FC)>=1 & odc0_d56$p_val_adj<=0.1,1]), length(odc1_d56[abs(odc1_d56$avg_log2FC)>=1 & odc1_d56$p_val_adj<=0.1,1]),  length(odc2_d56[abs(odc2_d56$avg_log2FC)>=1 & odc2_d56$p_val_adj<=0.1,1]),  length(opc_d56[abs(opc_d56$avg_log2FC)>=1 & opc_d56$p_val_adj<=0.1,1]),  length(tcell_d56[abs(tcell_d56$avg_log2FC)>=1 & tcell_d56$p_val_adj<=0.1,1])))


deg_FC1andPadj1_genes_UP<-list(Astrocyte_0=rownames(astro0_d56[astro0_d56$avg_log2FC>=1 & astro0_d56$p_val_adj<=0.05,]), Astrocyte_1=rownames(astro1_d56[astro1_d56$avg_log2FC>=1 & astro1_d56$p_val_adj<=0.05,]),
Astrocyte_3=rownames(astro3_d56[astro3_d56$avg_log2FC>=1 & astro3_d56$p_val_adj<=0.05,]),
DaN_0=rownames(dan0_d56[dan0_d56$avg_log2FC>=1 & dan0_d56$p_val_adj<=0.05,]),
DaN_1=rownames(dan1_d56[dan1_d56$avg_log2FC>=1 & dan1_d56$p_val_adj<=0.05,]),
DaN_2=rownames(dan2_d56[dan2_d56$avg_log2FC>=1 & dan2_d56$p_val_adj<=0.05,]),
GABA=rownames(gaba_d56[gaba_d56$avg_log2FC>=1 & gaba_d56$p_val_adj<=0.05,]),
Microglia_0=rownames(micro0_d56[micro0_d56$avg_log2FC>=1 & micro0_d56$p_val_adj<=0.05,]),
Microglia_1=rownames(micro1_d56[micro1_d56$avg_log2FC>=1 & micro1_d56$p_val_adj<=0.05,]),
Microglia_2=rownames(micro2_d56[micro2_d56$avg_log2FC>=1 & micro2_d56$p_val_adj<=0.05,]),
ODC_0=rownames(odc0_d56[odc0_d56$avg_log2FC>=1 & odc0_d56$p_val_adj<=0.05,]),
ODC_1=rownames(odc1_d56[odc1_d56$avg_log2FC>=1 & odc1_d56$p_val_adj<=0.05,]),
ODC_2=rownames(odc2_d56[odc2_d56$avg_log2FC>=1 & odc2_d56$p_val_adj<=0.05,]),
OPC=rownames(opc_d56[opc_d56$avg_log2FC>=1 & opc_d56$p_val_adj<=0.05,]),
Tcell=rownames(tcell_d56[tcell_d56$avg_log2FC>=1 & tcell_d56$p_val_adj<=0.05,])
)

deg_FC1andPadj1_genes_DOWN<-list(Astrocyte_0=rownames(astro0_d56[astro0_d56$avg_log2FC<= -1 & astro0_d56$p_val_adj<=0.05,]), Astrocyte_1=rownames(astro1_d56[astro1_d56$avg_log2FC<= -1 & astro1_d56$p_val_adj<=0.05,]),
Astrocyte_3=rownames(astro3_d56[astro3_d56$avg_log2FC<= -1 & astro3_d56$p_val_adj<=0.05,]),
DaN_0=rownames(dan0_d56[dan0_d56$avg_log2FC<= -1 & dan0_d56$p_val_adj<=0.05,]),
DaN_1=rownames(dan1_d56[dan1_d56$avg_log2FC<= -1 & dan1_d56$p_val_adj<=0.05,]),
DaN_2=rownames(dan2_d56[dan2_d56$avg_log2FC<= -1 & dan2_d56$p_val_adj<=0.05,]),
GABA=rownames(gaba_d56[gaba_d56$avg_log2FC<= -1 & gaba_d56$p_val_adj<=0.05,]),
Microglia_0=rownames(micro0_d56[micro0_d56$avg_log2FC<= -1 & micro0_d56$p_val_adj<=0.05,]),
Microglia_1=rownames(micro1_d56[micro1_d56$avg_log2FC<= -1 & micro1_d56$p_val_adj<=0.05,]),
Microglia_2=rownames(micro2_d56[micro2_d56$avg_log2FC<= -1 & micro2_d56$p_val_adj<=0.05,]),
ODC_0=rownames(odc0_d56[odc0_d56$avg_log2FC<= -1 & odc0_d56$p_val_adj<=0.05,]),
ODC_1=rownames(odc1_d56[odc1_d56$avg_log2FC<= -1 & odc1_d56$p_val_adj<=0.05,]),
ODC_2=rownames(odc2_d56[odc2_d56$avg_log2FC<= -1 & odc2_d56$p_val_adj<=0.05,]),
OPC=rownames(opc_d56[opc_d56$avg_log2FC<= -1 & opc_d56$p_val_adj<=0.05,]),
Tcell=rownames(tcell_d56[tcell_d56$avg_log2FC<= -1 & tcell_d56$p_val_adj<=0.05,])
)

pdf("deg_FC1andPadj1_ALL_numbers.pdf",10,3)
ggplot(deg_FC1andPadj1_ALL_numbers_melt,aes(x = cellType, y = variable,fill = value))+
    geom_tile() + scale_fill_gradient2(high = "red",mid = "red", low = "white",midpoint = 2500)+
    geom_tile() + theme(axis.text.x = element_text( color = "black",size = 10, angle = 45,hjust=1)) + geom_text(aes(label = round(value, 1))) 
dev.off()


jaccard <- function(a, b) {
    intersection = length(intersect(a, b))
    union = length(a) + length(b) - intersection
    return (intersection/union)
}

jac_ind<-data.frame(cellType=c("Astrocyte_0","Astrocyte_1","Astrocyte_3","DaN_0","DaN_1","DaN_2","GABA","Microglia_0","Microglia_1","Microglia_2","ODC_0","ODC_1","ODC_2","OPC","Tcells"),
JS_ILBD34_PD34=c(jaccard(deg_FC1andPadj05_ILBD34_genes$Astrocyte_0, deg_FC1andPadj05_PD34_genes$Astrocyte_0),
jaccard(deg_FC1andPadj05_ILBD34_genes$Astrocyte_1, deg_FC1andPadj05_PD34_genes$Astrocyte_1),
jaccard(deg_FC1andPadj05_ILBD34_genes$Astrocyte_3, deg_FC1andPadj05_PD34_genes$Astrocyte_3),
jaccard(deg_FC1andPadj05_ILBD34_genes$DaN_0, deg_FC1andPadj05_PD34_genes$DaN_0),
jaccard(deg_FC1andPadj05_ILBD34_genes$DaN_1, deg_FC1andPadj05_PD34_genes$DaN_1),
jaccard(deg_FC1andPadj05_ILBD34_genes$DaN_2, deg_FC1andPadj05_PD34_genes$DaN_2),
jaccard(deg_FC1andPadj05_ILBD34_genes$GABA, deg_FC1andPadj05_PD34_genes$GABA),
jaccard(deg_FC1andPadj05_ILBD34_genes$Microglia_0, deg_FC1andPadj05_PD34_genes$Microglia_0),
jaccard(deg_FC1andPadj05_ILBD34_genes$Microglia_1, deg_FC1andPadj05_PD34_genes$Microglia_1),
jaccard(deg_FC1andPadj05_ILBD34_genes$Microglia_2, deg_FC1andPadj05_PD34_genes$Microglia_2),
jaccard(deg_FC1andPadj05_ILBD34_genes$ODC_0, deg_FC1andPadj05_PD34_genes$ODC_0),
jaccard(deg_FC1andPadj05_ILBD34_genes$ODC_1, deg_FC1andPadj05_PD34_genes$ODC_1),
jaccard(deg_FC1andPadj05_ILBD34_genes$ODC_2, deg_FC1andPadj05_PD34_genes$ODC_2),
jaccard(deg_FC1andPadj05_ILBD34_genes$OPC, deg_FC1andPadj05_PD34_genes$OPC),
jaccard(deg_FC1andPadj05_ILBD34_genes$Tcell, deg_FC1andPadj05_PD34_genes$Tcell)),
JS_PD34_PD56=c(jaccard(deg_FC1andPadj05_PD56_genes$Astrocyte_0, deg_FC1andPadj05_PD34_genes$Astrocyte_0),
jaccard(deg_FC1andPadj05_PD56_genes$Astrocyte_1, deg_FC1andPadj05_PD34_genes$Astrocyte_1),
jaccard(deg_FC1andPadj05_PD56_genes$Astrocyte_3, deg_FC1andPadj05_PD34_genes$Astrocyte_3),
jaccard(deg_FC1andPadj05_PD56_genes$DaN_0, deg_FC1andPadj05_PD34_genes$DaN_0),
jaccard(deg_FC1andPadj05_PD56_genes$DaN_1, deg_FC1andPadj05_PD34_genes$DaN_1),
jaccard(deg_FC1andPadj05_PD56_genes$DaN_2, deg_FC1andPadj05_PD34_genes$DaN_2),
jaccard(deg_FC1andPadj05_PD56_genes$GABA, deg_FC1andPadj05_PD34_genes$GABA),
jaccard(deg_FC1andPadj05_PD56_genes$Microglia_0, deg_FC1andPadj05_PD34_genes$Microglia_0),
jaccard(deg_FC1andPadj05_PD56_genes$Microglia_1, deg_FC1andPadj05_PD34_genes$Microglia_1),
jaccard(deg_FC1andPadj05_PD56_genes$Microglia_2, deg_FC1andPadj05_PD34_genes$Microglia_2),
jaccard(deg_FC1andPadj05_PD56_genes$ODC_0, deg_FC1andPadj05_PD34_genes$ODC_0),
jaccard(deg_FC1andPadj05_PD56_genes$ODC_1, deg_FC1andPadj05_PD34_genes$ODC_1),
jaccard(deg_FC1andPadj05_PD56_genes$ODC_2, deg_FC1andPadj05_PD34_genes$ODC_2),
jaccard(deg_FC1andPadj05_PD56_genes$OPC, deg_FC1andPadj05_PD34_genes$OPC),
jaccard(deg_FC1andPadj05_PD56_genes$Tcell, deg_FC1andPadj05_PD34_genes$Tcell)))


```

### Pathway analysis

```{r GOenrich_cellType, echo=TRUE}
library(topGO)

xx <- annFUN.org("BP", mapping = "org.Hs.eg.db", ID = "symbol")
allGenes <- unique(unlist(xx))

listGenesDE1<-as.character(rownames(df_w_test_level1[order(-df_w_test_level1$Astrocyte),])[1:15000])
listGenesDE1_fdr01<-as.character(deg_FC1andPadj1_genes_UP$Astrocyte_0)
universeGenes<-as.character(allGenes[allGenes%in%listGenesDE1])
geneList <- factor(as.integer(universeGenes %in% listGenesDE1_fdr01))
names(geneList)<-universeGenes
GOdata <- new("topGOdata",
              ontology = "BP",
              allGenes = geneList,
              nodeSize = 10,
              annot = annFUN.org, 
              mapping = "org.Hs.eg.db",
              ID = "symbol")
GOenrich<-runTest(GOdata, algorithm = "classic", statistic = "fisher")
resGO_deg_pd56_astrocyte0_up <- GenTable(GOdata, classic = GOenrich, ranksOf = "classic", topNodes = 100)


```


### Pseudotime analysis for each cell type

```{r pseudotime_cellType, echo=TRUE}


```

### Cell-cell communication analysis


### Coexpression network analysis
