---
title: "Figure_2"
author: "Viola Volpato"
date: 'Last update: `r date()`'
output:
  html_document:
    fig_height: 5
    fig_width: 5
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
      toc_depth: 5
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---


```{r clean r session, include=FALSE}
rm(list = ls())
```

### Install and load library

```{r load lib, echo=TRUE}
library(ggplot2)
library(Seurat)
library(RColorBrewer)
library(topGO)
```


### Load data

```{r get raw data, echo=TRUE}
load("/nfs/dri/02/rdscw/shared/webber/SNatlas_icell8_Novaseq/manuscript_data/sn_atlas_processed.RData")

sn_atlas_processed <- NormalizeData(sn_atlas_processed)
sn_atlas_processed <- FindVariableFeatures(sn_atlas_processed, selection.method = "vst", nfeatures = 2000)
sn_atlas_processed <- ScaleData(sn_atlas_processed)
sn_atlas_processed <- RunPCA(sn_atlas_processed, features = VariableFeatures(object = sn_atlas_processed))
sn_atlas_processed <- FindNeighbors(sn_atlas_processed, dims = 1:10)
sn_atlas_processed <- FindClusters(sn_atlas_processed, resolution = 0.6)
sn_atlas_processed <- RunUMAP(sn_atlas_processed, dims = 1:10)

```

### Find cell type specific gene markers 

```{r gene markers, echo=TRUE}

# Method 1 (used in the manuscript):
# to be done for each cell type and subtype in controls

# level 1:

list_w_stat<-c()
df_w_test<-c()
signed_rank = function(x) sign(x) * rank(abs(x))
metadataALL<-as.data.frame(sn_atlas_processed@meta.data)
metadataALL_CTR<-metadataALL[metadataALL$Disease=="CTR",]
data<-as.matrix(GetAssayData(sn_atlas_processed, slot = "counts"))
data<-data[,colnames(data)%in%rownames(metadataALL_CTR)]
list_cell <- as.array(unique(metadataALL_CTR$CellType))
list_gene <- row.names(data)

compute_w_val<-function(gene_ref,cell_ref,matrix_expr,info_cell) {
    n_cell<- ncol(data)
    X<- matrix(-1, nrow = n_cell, ncol = 1)
    X[which(info_cell$CellSubType==cell_ref),1]<-1
    Y=t(data[gene_ref,])
    df<-data.frame(y=t(Y),x=X)
    colnames(df)<-c("y","x")
    linearMod <- lm(signed_rank(y) ~ x, data=df)
    val<-summary(linearMod)
    list_val<-val$coefficients[2,3]
    return(val$coefficients[2,3]) ## w-statisc value
}

for (i in c(1:length(list_cell))) {
    cell_ref=list_cell[i]
    print("W test")
    print(list_cell[i])
    list_w_stat<-sapply(list_gene,compute_w_val,cell_ref=list_cell[i],matrix_expr=data,info_cell=metadataALL_CTR)
    if(!exists("df_w_test")) {
        df_w_test<-data.frame(list_w_stat)
    } else {
        df_w_test<-cbind(df_w_test,list_w_stat)
    }
}
colnames(df_w_test) <- list_cell
write.table(df_w_test,"Wtest_level1",quote=F,sep="\t")

# level 2:

list_w_stat<-c()
df_w_test<-c()
signed_rank = function(x) sign(x) * rank(abs(x))
metadataALL<-as.data.frame(sn_atlas_processed@meta.data)
metadataALL_CTR<-metadataALL[metadataALL$Disease=="CTR",]
metadataALL_CTR<-metadataALL_CTR[metadataALL_CTR$CellType=="ODC",]
data<-as.matrix(GetAssayData(sn_atlas_processed, slot = "counts"))
data<-data[,colnames(data)%in%rownames(metadataALL_CTR)]
list_cell <- as.array(unique(metadataALL_CTR$CellSubType))
list_gene <- row.names(data)

compute_w_val<-function(gene_ref,cell_ref,matrix_expr,info_cell) {
    n_cell<- ncol(data)
    X<- matrix(-1, nrow = n_cell, ncol = 1)
    X[which(info_cell$CellSubType==cell_ref),1]<-1
    Y=t(data[gene_ref,])
    df<-data.frame(y=t(Y),x=X)
    colnames(df)<-c("y","x")
    linearMod <- lm(signed_rank(y) ~ x, data=df)
    val<-summary(linearMod)
    list_val<-val$coefficients[2,3]
    return(val$coefficients[2,3]) ## w-statisc value
}

for (i in c(1:length(list_cell))) {
    cell_ref=list_cell[i]
    print("W test")
    print(list_cell[i])
    list_w_stat<-sapply(list_gene,compute_w_val,cell_ref=list_cell[i],matrix_expr=data,info_cell=metadataALL_CTR)
    if(!exists("df_w_test")) {
        df_w_test<-data.frame(list_w_stat)
    } else {
        df_w_test<-cbind(df_w_test,list_w_stat)
    }
}
colnames(df_w_test) <- list_cell
write.table(df_w_test,"Wtest_ODCs",quote=F,sep="\t")



# Method 2:

Idents(sn_atlas_processed)<-sn_atlas_processed$CellType
clusterALLMarkers <- FindAllMarkers(sn_atlas_processed, only.pos = FALSE, min.pct = 0.1, thresh.use = 0.2)

```

### Prepare for MAGMA analysis 

```{r magma, echo=TRUE}

# level 1:

df_w_test_2p<-data.frame(cellt=c(rep("ODC",500),rep("Astrocyte",500),rep("DaN",500),rep("GABA",500),rep("OPC",500),rep("Microglia",500),rep("Tcell",500)),id=c(rownames(df_w_test[order(-df_w_test$ODC),])[1:500],rownames(df_w_test[order(-df_w_test$Astrocyte),])[1:500],rownames(df_w_test[order(-df_w_test$DaN),])[1:500],rownames(df_w_test[order(-df_w_test$GABA),])[1:500],rownames(df_w_test[order(-df_w_test$OPC),])[1:500],rownames(df_w_test[order(-df_w_test$Microglia),])[1:500],rownames(df_w_test[order(-df_w_test$Tcell),])[1:500]))

NCBI37.3.gene.loc<-read.delim("NCBI37.3.gene.loc",h=F)
names(NCBI37.3.gene.loc)[6]<-"id"
df<-merge(df_w_test_2p[,1:2],NCBI37.3.gene.loc,by=c("id"))
list_gene<-c()
for(m in unique(df$cellt)){
 val<-c(m,as.character(df[df$cellt==m,3]))
 val<-paste(val,collapse =" ")
 list_gene<-c(list_gene,val)
}
write.table(data.frame(list_gene),file="input_magma_level1_2p",quote=FALSE,row.names=FALSE,col.names=FALSE,sep="\t")

# Create heatmap with results:

magma_pd50k_L1_ALL<-read.table("magma_pd50k_L1_ALL",h=T)
magma_pd50k_L1_ALL$expr <-factor(magma_pd50k_L1_ALL$expr, levels=as.character(unique(magma_pd50k_L1_ALL$expr)))
ggplot(magma_pd50k_L1_ALL,aes(x = expr, y = celltype,fill = -log(pvalue)))+
     geom_tile() + scale_fill_gradient2(high = "red", low = "white",midpoint=2.995732)+
     geom_tile()


```

### Cell type-specific PPI networks (Figure 2)

```{r cellt_PPI, echo=TRUE}
library(igraph)

# to be done for DaN_3, ODC_2 and OPC (where PD genetic risk converged)

ppi_net<-read.delim("ppi_net_new2023short",h=F)
ppi_net_dan3top1000<-ppi_net[ppi_net[,1]%in%rownames(df_w_test_DaN[oder(-df_w_test_DaN$DaN_3),])[1:1000] & ppi_net[,2]%in%rownames(df_w_test_DaN[oder(-df_w_test_DaN$DaN_3),])[1:1000] ,]
ppi_net_dan3top1000_genes<-unique(c(as.character(ppi_net_dan3top1000[,1]),as.character(ppi_net_dan3top1000[,2])))

net_1 <- graph_from_data_frame(d= ppi_net_dan3top1000, vertices= ppi_net_dan3top1000_genes, directed=F)
cl_net_1<-cluster_louvain(net_1)
memb_net_1<-as.matrix(membership(cl_net_1))

memb_net_dan3top1000ppi_df<-data.frame(id=rownames(memb_net_1),module=memb_net_1)

# run GO enrichment for each module:

xx <- annFUN.org("BP", mapping = "org.Hs.eg.db", ID = "symbol")
allGenes <- unique(unlist(xx))
listGenesDE1<-as.character(rownames(df_w_test_DaN[oder(-df_w_test_DaN$DaN_3),])[1:10000])
listGenesDE1_fdr01<-as.character(memb_net_dan3top1000ppi_df[memb_net_dan3top1000ppi_df$module==1,1])
universeGenes<-as.character(allGenes[allGenes%in%listGenesDE1])
geneList <- factor(as.integer(universeGenes %in% listGenesDE1_fdr01))
names(geneList)<-universeGenes
GOdata <- new("topGOdata",
              ontology = "BP",
              allGenes = geneList,
              nodeSize = 10,
              annot = annFUN.org, 
              mapping = "org.Hs.eg.db",
              ID = "symbol")
GOenrich<-runTest(GOdata, algorithm = "classic", statistic = "fisher")
resGO_memb_net_dan3top1000ppi_M1 <- GenTable(GOdata, classic = GOenrich, ranksOf = "classic", topNodes = 100)

# create final DotPlot with top enriched GO terms for any PPI modules in DaN_3, ODC_2 and OPC:

GO_toPlot<-read.delim("GO_toPlot_PPImod_dan3_odc2_opc",h=T)
GO_toPlot$CellType_Mod<-paste(GO_toPlot$CellType,GO_toPlot$Module,sep="_")
GO_toPlot$Term <-factor(GO_toPlot$Term, levels=as.character(unique(GO_toPlot$Term)))
GO_toPlot$CellType_Mod <-factor(GO_toPlot$CellType_Mod, levels=as.character(unique(GO_toPlot$CellType_Mod)))

ggplot(GO_toPlot,aes(x =CellType_Mod , y = Term)) +  
    geom_point(aes(size= -log(as.numeric(P)), color= CellType)) + scale_size(range = c(4, 8)) +
    scale_color_manual(values=c("darkorange3","blue4","purple"))+ theme(axis.text.y = element_text( color = "black",size = 10)) + theme(axis.text.x = element_text( color = "black",size = 10, angle = 90,hjust=1)) + guides(colour = guide_legend(override.aes = list(size=8))) 


```
