---
title: "Figure_5"
author: "Viola Volpato"
date: 'Last update: `r date()`'
output:
  html_document:
    fig_height: 5
    fig_width: 5
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
      toc_depth: 5
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---


```{r clean r session, include=FALSE}
rm(list = ls())
```

### Install and load library

```{r load lib, echo=TRUE}
library(ggplot2)
library(Seurat)
library(RColorBrewer)
```


### Load data

```{r get raw data, echo=TRUE}
load("/nfs/dri/02/rdscw/shared/webber/SNatlas_icell8_Novaseq/manuscript_data/sn_atlas_processed.RData")

sn_atlas_processed <- NormalizeData(sn_atlas_processed)
sn_atlas_processed <- FindVariableFeatures(sn_atlas_processed, selection.method = "vst", nfeatures = 2000)
sn_atlas_processed <- ScaleData(sn_atlas_processed)
sn_atlas_processed <- RunPCA(sn_atlas_processed, features = VariableFeatures(object = sn_atlas_processed))
sn_atlas_processed <- FindNeighbors(sn_atlas_processed, dims = 1:10)
sn_atlas_processed <- FindClusters(sn_atlas_processed, resolution = 0.6)
sn_atlas_processed <- RunUMAP(sn_atlas_processed, dims = 1:10)

```

### Cell state transition DaN_1 to DaN_3 (Figure 5)

```{r dopa_ras_genes, echo=TRUE}
ras_genes<-read.delim("RASgenes.txt",h=F,stringsAsFactors = F)
dopamine_genes<-read.delim("DopamineKEGGpathway.txt",h=F,stringsAsFactors = F)

sn_atlas_processed_tmp<-subset(sn_atlas_processed,subset=CellType=="DaN")
sn_atlas_processed_tmp<-subset(sn_atlas_processed,subset=Disease=="CTR")
prot_cod_len<-read.delim("gene_length",h=T)
data<-as.matrix(GetAssayData(sn_atlas_processed_tmp, slot = "counts"))
prot_cod_m<-prot_cod_len[match(rownames(data),prot_cod_len[,1]),]
data <- sweep(data, 1, STATS = prot_cod_m$Gene_Length/1000, FUN = "/")
data[is.na(data)]<-0
data <- sweep(data, 2, STATS = colSums(data)/(10^6), FUN = "/")
SN_TPM_log_red<-log(data+1)

SN_TPM_log_red_raas<-SN_TPM_log_red[rownames(SN_TPM_log_red)%in%ras_genes[,1],]
SN_TPM_log_red_raas_t<-t(SN_TPM_log_red_raas)
SN_red_t_ord<-SN_TPM_log_red_raas_t
SN_red_t_ord<-as.data.frame(SN_red_t_ord)
SN_red_t_ord$cell_id<-sn_atlas_processed_tmp$CellSubType
SN_TPM_log_red_raas_t_melt<-melt(SN_red_t_ord)


ggplot(SN_TPM_log_red_raas_t_melt,aes(x=variable,y=value,fill=cell_id))+
    geom_violin(trim=T, scale="width", adjust=0.8)+scale_fill_manual(values=c("lightgoldenrod1","goldenrod","tan1","darkorange3"))+
    theme_bw()

```



```{r state_transition, echo=TRUE}

sn_atlas_processed_tmp<-subset(sn_atlas_processed,subset=CellSubType=="DaN_1" | CellSubType=="DaN_3")
sn_atlas_processed_tmp<-subset(sn_atlas_processed,subset=Disease=="CTR")
sce_dans <- as.SingleCellExperiment(sn_atlas_processed_tmp, assay = "RNA")
sce_dans <- slingshot(sce_dans, reducedDim = 'UMAP', clusterLabels = 'CellSubType')
meta_toplot<-data.frame(ps=sce_dans$slingPseudotime_1,cellt=sce_dans$CellSubType)
ggplot(meta_toplot, aes(x=ps, fill=cellt)) +
geom_density(alpha=.5) + theme_bw()

prot_cod_len<-read.delim("gene_length",h=T)
data<-as.matrix(GetAssayData(sn_atlas_processed_tmp, slot = "counts"))
prot_cod_m<-prot_cod_len[match(rownames(data),prot_cod_len[,1]),]
data <- sweep(data, 1, STATS = prot_cod_m$Gene_Length/1000, FUN = "/")
data[is.na(data)]<-0
data <- sweep(data, 2, STATS = colSums(data)/(10^6), FUN = "/")
SN_TPM_log_red<-log(data+1)
X_filtered <- SN_TPM_log_red[rowMeans(SN_TPM_log_red) > 0.1 & rowMeans(SN_TPM_log_red > 0) > 0.2,]
sde_dan <- switchde(X_filtered, sce_dans$slingPseudotime_1)
sde_dan <-arrange(sde_dan,qval)

sde_dan<-sde_dan[sde_dan$qval<0.01 & abs(sde_dan$k)>0.03,]

# alteratively:
dan_1and3_ctr_switchde<-read.delim("dan_1and3_ctr_switchde",h=T)
dan_1and3_ctr_switchde<-dan_1and3_ctr_switchde[order(dan_1and3_ctr_switchde$t0),]
dan_1and3_ctr_switchde$t0_sc<-rescale(dan_1and3_ctr_switchde$t0,to = c(0,19))
dan_1and3_ctr_switchde<-dan_1and3_ctr_switchde[dan_1and3_ctr_switchde$qval<=0.05,]


# GO enrichment plot for genes along cell state transition trajectory divided in three main intervals (or time points) and based on PPI gene modules:
dan_1and3_ctr_switchde_t5<-dan_1and3_ctr_switchde[dan_1and3_ctr_switchde$t0_sc <= 9,]
dan_1and3_ctr_switchde_t7<-dan_1and3_ctr_switchde[dan_1and3_ctr_switchde$t0_sc > 9 & dan_1and3_ctr_switchde$t0_sc<=11,]
dan_1and3_ctr_switchde_t8<-dan_1and3_ctr_switchde[dan_1and3_ctr_switchde$t0_sc > 11,]

ppi_net_dan3dan1_t5<-ppi_net[ppi_net[,1]%in%dan_1and3_ctr_switchde_t5$gene & ppi_net[,2]%in%dan_1and3_ctr_switchde_t5$gene ,]
ppi_net_dan3dan1_t5_genes<-unique(c(as.character(ppi_net_dan3dan1_t5[,1]),as.character(ppi_net_dan3dan1_t5[,2])))

net_1 <- graph_from_data_frame(d= ppi_net_dan3dan1_t5, vertices= ppi_net_dan3dan1_t5_genes, directed=F)
cl_net_1<-cluster_louvain(net_1)
memb_net_1<-as.matrix(membership(cl_net_1))
memb_net_dan3dan1_t5_df<-data.frame(id=rownames(memb_net_1),module=memb_net_1)

xx <- annFUN.org("BP", mapping = "org.Hs.eg.db", ID = "symbol")
allGenes <- unique(unlist(xx))
listGenesDE1<-as.character(rownames(Wtest_counts_L1[order(Wtest_counts_L1$DaN),])[1:15000])
listGenesDE1_fdr01<-as.character(memb_net_dan3dan1_t5_df[memb_net_dan3dan1_t5_df$module==1,1])
universeGenes<-as.character(allGenes[allGenes%in%listGenesDE1])
geneList <- factor(as.integer(universeGenes %in% listGenesDE1_fdr01))
names(geneList)<-universeGenes
GOdata <- new("topGOdata",
              ontology = "BP",
              allGenes = geneList,
              nodeSize = 10,
              annot = annFUN.org, 
              mapping = "org.Hs.eg.db",
              ID = "symbol")
GOenrich<-runTest(GOdata, algorithm = "classic", statistic = "fisher")
resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M1 <- GenTable(GOdata, classic = GOenrich, ranksOf = "classic", topNodes = 100)

# to be repeated for all modules across all three identified intervals to then plot the results:
GO_toPlot<-data.frame(
    Term=c(
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M1$Term[c(8,17,47)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M2$Term[c(2,23,94)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M3$Term[c(3,11)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M4$Term[c(1,15)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M5$Term[c(5,10)],       
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M6$Term[c(1,21)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M7$Term[c(25)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M8$Term[c(9,37,56)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M9$Term[c(15,38)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M10$Term[c(8)]),
    Module=c("M1","M1","M1","M2","M2","M2","M3","M3","M4","M4", "M5","M5","M6","M6","M7","M8","M8","M8","M9","M9","M10"),
    
    Interval=c(rep("Int_5",21)),
    
    P=c(
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M1$classic[c(8,17,47)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M2$classic[c(2,23,94)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M3$classic[c(3,11)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M4$classic[c(1,15)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M5$classic[c(5,10)],       
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M6$classic[c(1,21)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M7$classic[c(25)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M8$classic[c(9,37,56)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M9$classic[c(15,38)],
        resGO_dan_1and3_ctr_switchde_tcut5_ppiShort_M10$classic[c(8)]))


write.table(GO_toPlot,"GO_toPlot",quote=F,sep="\t",row.names = F)
GO_toPlot<-read.delim("GO_toPlot",h=T)
GO_toPlot$Int_Mod<-paste(GO_toPlot$Interval,GO_toPlot$Module,sep="_")
GO_toPlot$Term <-factor(GO_toPlot$Term, levels=as.character(unique(GO_toPlot$Term)))
GO_toPlot$Module <-factor(GO_toPlot$Module, levels=as.character(unique(GO_toPlot$Module)))

ggplot(GO_toPlot,aes(x = Module , y = Term)) +  
    geom_point(aes(size= -log(as.numeric(P)), color= Interval)) + scale_size(range = c(4, 8)) +
    scale_color_manual(values=c("orange1"))+ theme(axis.text.y = element_text( color = "black",size = 10)) + theme(axis.text.x = element_text( color = "black",size = 10, angle = 90,hjust=1)) + guides(colour = guide_legend(override.aes = list(size=8))) 




GO_toPlot<-data.frame(
    Term=c(
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M1$Term[c(1,3,4)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M2$Term[c(15)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M3$Term[c(6,11,15)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M4$Term[c(8,12,14)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M5$Term[c(1,19)],       
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M6$Term[c(3)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M7$Term[c(7,37)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M8$Term[c(16)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M9$Term[c(6,19)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M10$Term[c(1,16,27,63)],
resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M11$Term[c(1,3,6,12)],
resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M12$Term[c(1,12,29)],
resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M13$Term[c(6,7,25)],
resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M14$Term[c(6)],
resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M15$Term[c(13,17,58)],
resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M16$Term[c(26,35)]),

    Module=c("M1","M1","M1","M2","M3","M3","M3","M4","M4","M4", "M5","M5","M6","M7","M7","M8","M9","M9","M10","M10","M10","M10","M11","M11","M11","M11","M12","M12","M12","M13","M13","M13","M14","M15","M15","M15","M16","M16"),
    
    Interval=c(rep("Int_7",38)),
    
    P=c(
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M1$classic[c(1,3,4)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M2$classic[c(15)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M3$classic[c(6,11,15)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M4$classic[c(8,12,14)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M5$classic[c(1,19)],       
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M6$classic[c(3)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M7$classic[c(7,37)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M8$classic[c(16)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M9$classic[c(6,19)],
        resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M10$classic[c(1,16,27,63)],
resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M11$classic[c(1,3,6,12)],
resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M12$classic[c(1,12,29)],
resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M13$classic[c(6,7,25)],
resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M14$classic[c(6)],
resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M15$classic[c(13,17,58)],
resGO_dan_1and3_ctr_switchde_tcut7_ppiShort_M16$classic[c(26,35)]))


write.table(GO_toPlot,"GO_toPlot",quote=F,sep="\t",row.names = F)
GO_toPlot<-read.delim("GO_toPlot",h=T)
GO_toPlot$Int_Mod<-paste(GO_toPlot$Interval,GO_toPlot$Module,sep="_")
GO_toPlot$Term <-factor(GO_toPlot$Term, levels=as.character(unique(GO_toPlot$Term)))
GO_toPlot$Module <-factor(GO_toPlot$Module, levels=as.character(unique(GO_toPlot$Module)))

ggplot(GO_toPlot,aes(x = Module , y = Term)) +  
    geom_point(aes(size= -log(as.numeric(P)), color= Interval)) + scale_size(range = c(4, 8)) +
    scale_color_manual(values=c("orange3"))+ theme(axis.text.y = element_text( color = "black",size = 10)) + theme(axis.text.x = element_text( color = "black",size = 10, angle = 90,hjust=1)) + guides(colour = guide_legend(override.aes = list(size=8))) 


GO_toPlot<-data.frame(
    Term=c(
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M1$Term[c(5,15)],
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M2$Term[c(6,33,38)],
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M3$Term[c(2)],
        
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M5$Term[c(26,76)],       
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M6$Term[c(3,12,13,93)],
        
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M8$Term[c(4,47)],
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M9$Term[c(12,14,29,31)],
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M10$Term[c(7,43)],
resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M11$Term[c(1,8)],
resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M12$Term[c(6,10)],
resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M13$Term[c(21,76)]),

    Module=c("M1","M1","M2","M2","M2","M3","M5","M5","M6","M6","M6","M6","M8","M8","M9","M9","M9","M9","M10","M10","M11","M11","M12","M12","M13","M13"),
    
    Interval=c(rep("Int_8",26)),
    
    P=c(
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M1$classic[c(5,15)],
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M2$classic[c(6,33,38)],
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M3$classic[c(2)],
        
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M5$classic[c(26,76)],       
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M6$classic[c(3,12,13,93)],
        
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M8$classic[c(4,47)],
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M9$classic[c(12,14,29,31)],
        resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M10$classic[c(7,43)],
resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M11$classic[c(1,8)],
resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M12$classic[c(6,10)],
resGO_dan_1and3_ctr_switchde_tcut8_ppiShort_M13$classic[c(21,76)]))


write.table(GO_toPlot,"GO_toPlot",quote=F,sep="\t",row.names = F)
GO_toPlot<-read.delim("GO_toPlot",h=T)
GO_toPlot$Int_Mod<-paste(GO_toPlot$Interval,GO_toPlot$Module,sep="_")
GO_toPlot$Term <-factor(GO_toPlot$Term, levels=as.character(unique(GO_toPlot$Term)))
GO_toPlot$Module <-factor(GO_toPlot$Module, levels=as.character(unique(GO_toPlot$Module)))

ggplot(GO_toPlot,aes(x = Module , y = Term)) +  
    geom_point(aes(size= -log(as.numeric(P)), color= Interval)) + scale_size(range = c(4, 8)) +
    scale_color_manual(values=c("orange4"))+ theme(axis.text.y = element_text( color = "black",size = 10)) + theme(axis.text.x = element_text( color = "black",size = 10, angle = 90,hjust=1)) + guides(colour = guide_legend(override.aes = list(size=8))) 



pseud_dan_range<-cut(meta_toplot$ps, c(0, 5,10,15,20), include.lowest=TRUE)
sn_atlas_processed_tmp$ps_range<-pseud_dan_range

dans_ras<-AverageExpression(sn_atlas_processed_tmp,features = ras[,1],group.by = "ps_range")
dans_ras<-data.frame(dans_ras$RNA)
dans_ras_melt<-melt(dans_ras)

ggplot(dans_ras_melt, aes(x = gene, y = ps_range, fill = value)) +
  geom_tile(color = "white",
            lwd = 1.5,
            linetype = 1) +
  scale_fill_gradient(low = "blue",mid="white", high = "red")


```
